### ISSUE TITLE
[Feature Request] Configurable keyFilePath, projectId and emulatorHost

### ISSUE THREAD

**Issue by ricktap** [petitpress/gps-messenger-bundle#5]
Hi,

in order for us to deploy and use this bundle inside a Kubernetes Cluster, we would like to store our credentials inside a secret. We would then configure the bundle with a keyFilePath or have the whole configuration inside a ConfigMap including the keyFile option.

We are working on this feature right now and provide it as a pull request in the next few days. 

The feature would still allow for the environment variable to be loaded, as it is right now. The order of credential loading is described in the [google-cloud-php packages documentation](https://github.com/googleapis/google-cloud-php/blob/master/AUTHENTICATION.md).

The use of (new DotEnv())->usePutenv() is no longer given in Symfony 5.3 and above.

**Comment by chrishemmings** [comment]
@ricktap This might help you....

```yaml
framework:
    messenger:
        transports:
            saleor_product:
                dsn: 'gps://default'
                options:
                    topic:
                        name: "%env(GPS_TOPIC)%"
                    subscription:
                        name: "%env(GPS_SUBSCRIPTION)%"
                        pull:
                            maxMessages: 10
                    client_config:
                        keyFile: "%env(json:base64:GPS_KEY)%"
                        projectId: "%env(default::GPS_PROJECT)%"

```
Where `GPS_KEY` is the content of your key file, base64 encoded.
